services:
  web:
    container_name: uni
    build: .
    command: python3 manage.py runserver 0.0.0.0:8888
    ports:
     - "8888:8888"
    env_file:
      - ./.env.dev
    volumes:
      - ./src/db.sqlite3:/home/nonroot/db.sqlite3
      - ./src:/src