services:
  web:
    container_name: web
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:18
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/
    ports:
      - "5432:5432"
volumes:
  db-data: