- hosts: all
  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: latest
        update_cache: true
      become: true

    - name: Add user to the docker group
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        groups: docker
        append: true # don't remove any existing groups
      become: true

    - name: Reset connection to reflect group change
      ansible.builtin.meta: reset_connection

    - name: Build project image locally
      ansible.builtin.command: docker build -t uni ..
      delegate_to: 127.0.0.1

    - name: Export project image locally
      community.docker.docker_image:
        name: uni
        archive_path: /tmp/uni-img.tar
        source: local
      delegate_to: 127.0.0.1

    - name: Copy archive to server
      ansible.builtin.copy:
        src: /tmp/uni-img.tar
        dest: /tmp/uni-img.tar

    - name: Load image from archive
      community.docker.docker_image:
        name: uni
        source: load
        load_path: /tmp/uni-img.tar
        force_source: true

    - name: Spin up a container using the image
      community.docker.docker_container:
        name: uni
        image: uni
        state: started
        recreate: true