# Generated by Django 6.1.1 on 2026-09-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('details', models.TextField(blank=True, help_text='Detailed Description of the item.', null=True)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
