# Generated by Django 5.2 on 2026-10-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_item_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
